// Resolve WPF vs WinForms / System.Drawing name conflicts (UseWindowsForms=true + ImplicitUsings)
global using Application     = System.Windows.Application;
global using Brush           = System.Windows.Media.Brush;
global using Color           = System.Windows.Media.Color;
global using SolidColorBrush = System.Windows.Media.SolidColorBrush;
global using Point           = System.Windows.Point;
global using MouseEventArgs  = System.Windows.Input.MouseEventArgs;
global using KeyEventArgs    = System.Windows.Input.KeyEventArgs;
global using MessageBox      = System.Windows.MessageBox;
global using Clipboard       = System.Windows.Clipboard;
global using Brushes              = System.Windows.Media.Brushes;
global using HorizontalAlignment  = System.Windows.HorizontalAlignment;
global using VerticalAlignment    = System.Windows.VerticalAlignment;
